version: '3.8'

services:
  # Main Agent Service
  agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personal-ai-agent
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - VECTOR_DB_HOST=vector-db
      - VECTOR_DB_PORT=6333
    ports:
      - "8000:8000"  # API port
      - "8501:8501"  # UI port
    depends_on:
      - vector-db
    restart: unless-stopped
    networks:
      - agent-network

  # Vector Database Service (Qdrant)
  vector-db:
    image: qdrant/qdrant:latest
    container_name: vector-db
    volumes:
      - vector-db-data:/qdrant/storage
    ports:
      - "6333:6333"  # API port
      - "6334:6334"  # Web UI port
    environment:
      - QDRANT_ALLOW_CORS=true
    restart: unless-stopped
    networks:
      - agent-network

volumes:
  vector-db-data:
    driver: local

networks:
  agent-network:
    driver: bridge
