# Configuration file for Personal AI Agent

# Agent Core Configuration
agent:
  name: "Personal AI Agent"
  version: "1.0.0"
  description: "A personal AI agent similar to Manus AI"
  max_iterations: 50
  default_timeout: 300  # seconds

# LLM Configuration
llm:
  provider: "deepseek"
  model: "DeepSeek-R1-Distill-Qwen-7B"
  api_key: "${DEEPSEEK_API_KEY}"
  api_base: "https://api.deepseek.com/v1"
  max_tokens: 4096
  temperature: 0.7
  top_p: 0.95
  frequency_penalty: 0.0
  presence_penalty: 0.0
  timeout: 60  # seconds
  retry_attempts: 3
  retry_delay: 2  # seconds

# Embedding Configuration
embedding:
  provider: "deepseek"
  model: "deepseek-embedding"
  dimensions: 1536
  batch_size: 8

# Vector Database Configuration
vector_db:
  provider: "qdrant"
  host: "${VECTOR_DB_HOST}"
  port: ${VECTOR_DB_PORT}
  collection_name: "knowledge_base"
  distance_metric: "Cosine"
  vector_size: 1536

# Knowledge Module Configuration
knowledge:
  max_short_term_memory: 100
  max_long_term_memory: 10000
  relevance_threshold: 0.75
  memory_refresh_interval: 3600  # seconds

# Planning Module Configuration
planning:
  planning_method: "react"  # Options: "cot", "tot", "react"
  max_plan_steps: 20
  plan_revision_threshold: 0.3

# Tool Integration Configuration
tools:
  shell:
    enabled: true
    timeout: 30  # seconds
    max_output_size: 10240  # bytes
  
  file:
    enabled: true
    max_file_size: 10485760  # bytes (10MB)
    allowed_extensions: [".txt", ".md", ".py", ".js", ".html", ".css", ".json", ".yaml", ".yml"]
  
  browser:
    enabled: true
    timeout: 60  # seconds
    max_tabs: 5
    user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  
  information:
    enabled: true
    search_timeout: 30  # seconds
    max_results: 10
  
  message:
    enabled: true

# Logging Configuration
logging:
  level: "${LOG_LEVEL}"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "/app/logs/agent.log"
  max_file_size: 10485760  # bytes (10MB)
  backup_count: 5

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  debug: false
  cors_origins: ["*"]
  auth_enabled: false

# UI Configuration
ui:
  host: "0.0.0.0"
  port: 8501
  theme: "light"
  title: "Personal AI Agent"
  description: "A personal AI agent similar to Manus AI"
  logo_path: "/app/static/logo.png"
